### ISSUE TITLE
Installation issue: Minisig verification fails on Mac / Linux

### ISSUE THREAD

**Issue by sprocter** [sireum/logika#1]
I'm following the installation steps here: http://logika.sireum.org/doc/01-getting-started/index.html on Ubuntu 16.04. Using minisig to check the downloaded file (in step 1.1.1) results in the following error:

`Signature key id in ./sireum-v3-dev-ive-linux64.zip.minisig is 1C11D3D6BF9745A1
but the key id in the public key is 6464394871D4AE89`

@joeseibel gets a similar error trying to verify on Mac.

**Comment by robby-phd** [comment]
This should be filed in https://github.com/sireum/v3 as you are using v3 distribution. The minisig command listed in the website is outdated; it should be:

```
minisign -P RWShRZe/1tMRHAcQ2162Wq5FhU2ptktJdQxzUxvK0MwVjDYRC4JY87Fb -Vm <file>
```

We will update the website and v3's readme.
